### ISSUE TITLE
Tried to use it with react-bootstrap

### ISSUE THREAD

**Issue by arran4** [Lucifier129/react-lite#10]
I am not sure if it's my setup. However I got an issue at this line in react-bootstrap:
	var version = _react2['default'].version.split('.').map(parseFloat);
Seems the react object isn't populated with the version. 

(Error was,
Uncaught TypeError: Cannot read property 'split' of undefined
)

**Comment by Lucifier129** [comment]
hey, react-bootstrap use some special api of react, such as `ReactDOM.unstable_renderSubtreeIntoContainer` and `React.version`. I think it is a dirty way, but I still try to support react-bootstrap.

you can try again. use the new version(v0.0.7) of react-lite.

**Comment by arran4** [comment]
I just tried it:
Same error..

Email me and I can send you the project.

_react.version
undefined
_react2["default"].version
undefined
bundle.js:21816 Uncaught TypeError: Cannot read property 'split' of undefined

  "dependencies": {
    "bootstrap-sass": "^3.3.5",
    "jquery": "^2.1.4",
    "react-bootstrap": "^0.28.1",
    "react-lite": "0.0.7"
  },

**Comment by arran4** [comment]
Actually, works perfectly. Thanks!

**Comment by Lucifier129** [comment]
hi, I checkout the react-bootstrap repository, any run its doc/examples server with react-lite, find out some bug to fixed.

now the lastest version v0.0.8 will be better for you.

**Comment by arran4** [comment]
The drop downs don't work.. I am not sure if this is entirely related. But it still seems to work in general with 0.0.8..

See https://ide.c9.io/arran4/go-appengine-bootstrap-react-lite 
or
https://github.com/arran4/go-appengine-webpack-bootstrap-sass-react-lite-es6

**Comment by Lucifier129** [comment]
@arran4 see [README](https://github.com/Lucifier129/react-lite#what-can-react-lite-do)

react-lite(v0.0.11) support react-bootstrap now. a little difference with react.

**Comment by arran4** [comment]
The drop downs are definitely working now.. Thanks!
