### ISSUE TITLE
<img onError={...}/> does not fire

### ISSUE THREAD

**Issue by matthewoates** [Lucifier129/react-lite#100]
This works in react.

Working react example: https://jsfiddle.net/c2oeshsg/
Broken react-lite example: https://jsfiddle.net/kavLqzby/

**Comment by Lucifier129** [comment]
Thanks feedback, now it can work.

**Comment by matthewoates** [comment]
Awesome. Thanks for the quick response.

**Comment by liyikun** [comment]
映杰，，这个问题修复了吗？
