### ISSUE TITLE
More documentation comparing to react

### ISSUE THREAD

**Issue by matthewoates** [Lucifier129/react-lite#101]
Thanks again for the quick response on my earlier issue.

I'm using react-lite for a non-trivial project, and assuming it's successful I'd like to post about the performance of react vs react-lite in the project. I see most of the react API is mimicked with react-lite, but the docs don't explain why react-lite is smaller than react.

I suspect there are some expensive corner cases that react handles but react-lite does not. Can you elaborate on this?

**Comment by Lucifier129** [comment]
There are some information in the [react-lite-vs-react](https://github.com/Lucifier129/react-lite#react-lite-vs-react) of README.

The reasons of why react-lite is smaller than react is that

- react-lite do not need to support IE8 or ES3
- react-lite use the w3c event system which is native supported in modern browser, and  regular react has an complex custom event system. a lot of code in react is about this big feature.
- react-lite do not support server-side rendering.
- react is one of the biggest script size of virtual-dom implementation, virtual-dom, react-lite, preact, inferno, vue-v2 are all smaller than react.

**Comment by matthewoates** [comment]
Sounds good to me. I'll research this more when my project is more developed.
