### ISSUE TITLE
Possible reasons react-lite results in ~2KB bundle size reduction?

### ISSUE THREAD

**Issue by JohnAllen** [Lucifier129/react-lite#104]
Anyone have any thoughts?  I only got a ~2KB reduction and I thought it would be more like 17KB which is what the [Medium article I found](https://medium.com/@guyingjie129/five-reasons-about-why-you-should-try-react-lite-857dd52ecee3#.4tvpn48hd) claimed.

**Comment by Lucifier129** [comment]
You can try `webpack-bundle-analyzer` to analyzer the bundle, if you are using `webpack`
