### ISSUE TITLE
Select Value not selecting option

### ISSUE THREAD

**Issue by gpltaylor** [Lucifier129/react-lite#125]
When using "select" tag, the selected option is not displayed. 
This works in Chrome, but not IE or Edge.

**Expected**
Dropdown to show with the selected value picked in Edge or IE. 

**Actual** 
The first item is selected

**Example**
https://jsfiddle.net/xy99xexh/3/

**Comment by Lucifier129** [comment]
try `selected` attribute, it can work

```javascript
<option value="0" key="0">zero</option>
<option value="1" key="1">1</option>
<option selected={typeValue === 2} value="2" key="2">2</option>
 <option value="3" key="3">3</option>
<option value="4" key="4">4</option>
```
An `Option` component will be better

```javascript
function Option({ value, select, children }) {
  return <option selected={value === select} value={value}>{children}</options>
}
```

**Comment by gpltaylor** [comment]
Hi @Lucifier129 thank you for your response. We have implemented this solution, however, we get React warning to use value or defaultValue within the select tag. 

Do you think that React/lite will remove support for this? I want to limit technical debt for upgrading.

**Comment by Lucifier129** [comment]
@gpltaylor No, `selected` is a native dom property, I think react and react-lite will always support this feature.

**Comment by gpltaylor** [comment]
Thanx @Lucifier129 I will implement this shortcut. Will react-lite be updated to support this or do you want me to close this issue? It's working in some browsers and is a bug in React-lite (IMO)...

**Comment by Lucifier129** [comment]
Yeah, it is a bug of react-lite, let's keep this issue open until it has been resolved~

**Comment by gpltaylor** [comment]
Ta, and thank you for the effort you put into this project. 👍

**Comment by gpltaylor** [comment]
Hi @Lucifier129 I have submitted a pull request 
https://github.com/Lucifier129/react-lite/pull/127
