### ISSUE TITLE
How did you implement it?

### ISSUE THREAD

**Issue by ugin** [Lucifier129/react-lite#13]
Did you copy most of the implementation details from React or created your own `virtual-dom` implementation?

Great work by the way!

**Comment by Lucifier129** [comment]
the implementation of react-lite is different from other implementations([react](https://github.com/facebook/react) or [virtual-dom](https://github.com/Matt-Esch/virtual-dom)), it's much simple(for example, see [diff.js source code](https://github.com/Lucifier129/react-lite/blob/master/src/diff.js), it does'nt have `REORDER` type)

**Comment by mindreframer** [comment]
can be closed ;)

**Comment by ugin** [comment]
Yup, sorry, planned to ask about the event system too but looked at the code and figured out.
