### ISSUE TITLE
webpack alias example should be clearer

### ISSUE THREAD

**Issue by 2vek** [Lucifier129/react-lite#15]
Had to look up webpack documentation for this, But I think `resolve` key should be stated in example.
```js
// webpack.config.js
{
    resolve: {
        alias: {
            'react': 'react-lite',
            'react-dom': 'react-lite'
        }
    }
}
```

**Comment by Lucifier129** [comment]
thank for your suggestion.

README.md was updated, and now it would be clearer than before.

**Comment by 2vek** [comment]
Thanks :+1:
