### ISSUE TITLE
vchild.initTree is undefined

### ISSUE THREAD

**Issue by fritx** [Lucifier129/react-lite#16]
![image](https://cloud.githubusercontent.com/assets/6647633/12085294/6e6e448c-b2f9-11e5-9db9-ce6f2698b647.png)

It breaks when an `Object` appears

```js
// src/virtual-dom.js
	initTree: function initTree(parentNode) {
		var type = this.type;
		var props = this.props;

		var node = this.node = createElement$1(type, props);
		this.eachChildren(function (vchild) {

			console.log(vchild)   // added
			vchild.initTree(node);
		});
		appendNode(parentNode, node);
		this.attachRef();
	},
```

**Comment by fritx** [comment]
![image](https://cloud.githubusercontent.com/assets/6647633/12085338/fb3633b6-b2f9-11e5-97ed-1e9fcc4f671b.png)

**Comment by Lucifier129** [comment]
why the children list have an object which is not vaild(`react element`、`react component`、`string`)

**Comment by fritx** [comment]
@Lucifier129 oh that's an Immutable object written by my partners.
I fixed it when I changed `{list.map(xxxx)}` to  `{list.map(xxxx).toJS()}`.
In react, it works without the fix. Maybe react would call it automatically?
Maybe react-lite can also do it for us!
Btw, awesome work on react-lite!

**Comment by Lucifier129** [comment]
@fritx thank you.

react-lite has no plan to support that tansform`Immutable` object to native data structure as automatic, such as I think `React.createClass with autobind has bad smell`, it's hard to distinguish `native data/immutable data` and `autobind method/normal method`

sorry about that.

**Comment by fritx** [comment]
No problem!
I'm closing this as it is fixed ;)
