### ISSUE TITLE
can not work with react-router

### ISSUE THREAD

**Issue by pennsong** [Lucifier129/react-lite#17]
工兄弟, 我已经尽量简化了重现问题步骤, 如附件:
1) npm install
2) npm start

注释掉:
	resolve: {
		alias: {
			'react': 'react-lite',
			'react-dom': 'react-lite'
		}
	}
成功
没有注释掉就失败

请点解, 等待您的回复
[gyj.zip](https://github.com/Lucifier129/react-lite/files/77477/gyj.zip)

**Comment by Lucifier129** [comment]
好的，我看看。

**Comment by Lucifier129** [comment]
@pennsong React.isValidElement return fasle with <StatelessComponent />, now I had fixed it on version 0.0.12.

please try update react-lite to lastest version.

**Comment by Lucifier129** [comment]
close this issue. if has other problem, then reopen it.
