### ISSUE TITLE
component update clears innerHTML?

### ISSUE THREAD

**Issue by fritx** [Lucifier129/react-lite#19]
```jsx
<Editor ref="edit" id="editor" className="edit"
              style={{
                fontFamily: fields.fontFamily.value,
                fontSize: fields.fontSize.value,
                fontWeight: fields.fontBold.value ? 'bold' : 'normal',
                color: fields.fontColor.value,
              }}
              onKeyDown={(e)=>this.onKeyDown(e)}
              onInput={(e)=>this.onInput(e)}
              dangerouslySetInnerHTML={{__html: currConver.editor}} />
```

It seems the innerHTML clears when one of the css style updates.
When I switch back to react, it works.
Is it a bug of react-lite?

**Comment by Lucifier129** [comment]
I wonder the type of  `currConver.editor`, it's string or not?

since:
```javascript
let oldHtml = oldValue && oldValue.__html
let html = value && value.__html
if (!isStr(html)) {
  elem.innerHTML = ''
} else if (html !== oldHtml) {
  elem.innerHTML = html
}
```

**Comment by Lucifier129** [comment]
if `currConver.editor` is equal to undefined, innerHTML will also be clears.

Had better got a demo for debugging:)

**Comment by fritx** [comment]
Yes, you're right. It is `undefined` :cry: 
But this is different with React. Is it better to make them consistent? ;)

**Comment by Lucifier129** [comment]
@fritx That's ok, I will check the behavior about inneHTML in this case with react, and make them consistent.

**Comment by fritx** [comment]
Thanks! At this time, I prefer consistancy. Thank you!
But maybe in the future, react-lite's simple and lightweight wins!

**Comment by Lucifier129** [comment]
I think the version v0.0.13 of react-lite made consistancy with below change:

```javascript
let oldHtml = oldValue && oldValue.__html
let html = value && value.__html
if (html != null && html !== oldHtml) {
  elem.innerHTML = html
}
```

It won't be patched if html is equal to null or undefined such like regular react does.

try the lastest version to confirm this problem was resolved:)

BTW, I think regular react will provide lightweight version in the feature, or something like rollup \ tree shaking, make react-lite not necessary

 haha ~ just wait and see what will happen.

**Comment by fritx** [comment]
@Lucifier129 haha~ ok, wait a sec

**Comment by fritx** [comment]
Ok alright!
- [x] It won't be patched if html is equal to null or undefined
- [x] It will be patched if html is equal to empty string

**Comment by Lucifier129** [comment]
That's good:)

**Comment by dhenson02** [comment]
issue should be closed :+1:
