### ISSUE TITLE
this.refs sometimes equals to null

### ISSUE THREAD

**Issue by fritx** [Lucifier129/react-lite#22]
```jsx
  render() {
    return (
      <img className="avatar-one" ref="img"
        onLoad={()=>{
          console.log('onload this.refs', this.refs)
        }}
        onError={()=>{
          console.log('onerror this.refs', this.refs)
        }} />
    )
  }
```

Hey @Lucifier129 
In react-lite, I found that `this.refs` sometimes equals to null, called in `onLoad/onError` of `<img>` tag.
The probability is very small, but I can always reproduce it by very frequent rendering.
It causes a bug in my app.
And when I try the regular React, it's fine.

**Comment by Lucifier129** [comment]
I got the problem and try to fixed it in version 0.0.14.

Even the element has been removed, `onload/onerror` would still be triggered. react-lite will removeEvent all the event handler in its props at v0.0.14.

please update `react-lite`, and try again.

**Comment by Lucifier129** [comment]
sorry about misunderstand your description.

I had try many time about `onload/onerror`, and can't reappear `this.refs == null`.

**Comment by fritx** [comment]
But it seems that after upgrading react-lite, the problem is gone.

**Comment by Lucifier129** [comment]
OK:-)

Now which version of react-lite are you using?
