### ISSUE TITLE
Doesn't support react-portal

### ISSUE THREAD

**Issue by luandro** [Lucifier129/react-lite#23]
It doesn't work with [react-portal](https://github.com/tajo/react-portal). Just pointing out, close it if there's no work around or it isn't suppose to work.

Error:

```
ERROR in ./~/react-portal/portal.js
[0] Module not found: Error: Cannot resolve module 'react-lite/lib/CSSPropertyOperations' in /Users/project/node_modules/react-portal
```

**Comment by Lucifier129** [comment]
sorry, react-lite did not support accessed any `react/lib/*` path now.
