### ISSUE TITLE
filesize clarification

### ISSUE THREAD

**Issue by nickcolley** [Lucifier129/react-lite#26]
Neat project!

Is the filesize in the readme after compression + gzip?  could you clarify that and potentially compare directly with vanilla React?

Thanks!

**Comment by Lucifier129** [comment]
It sounds good.

Added `framework-size-comparison` part to README, can see it with this link: https://github.com/Lucifier129/react-lite#framework-size-comparison

**Comment by fritx** [comment]
:+1:

**Comment by nickcolley** [comment]
Thanks so much @Lucifier129, can I be a real pain and ask is that with gzip? It says minified but I'm not sure?

I'd have two columns: `minified` and `minfied+gzip`

The `minified` gives you an idea of how much code needs to be executed once it's unpacked, the `minfied + gzip` gives you an idea of how long it'll take to get to your user.

You could use something like https://github.com/sindresorhus/gzip-size + https://github.com/sindresorhus/pretty-bytes

Related thoughts: https://aerotwist.com/blog/the-cost-of-frameworks/

Thanks again for your patience :+1:

**Comment by Lucifier129** [comment]
@nickcolley I think `minified ` size was enough to show how lightweight about react-lite.

Even without `gzip`, react-lite is small than many other library with `gzip`, LOL

**Comment by nickcolley** [comment]
Either way you should clarify if you're using gzip to make your calculations, most people who care about  performance want to know minified+gzip since that's what users will get.

**Comment by tejacques** [comment]
@nickcolley if it wasn't clear, looking at https://github.com/Lucifier129/react-lite/tree/master/dist clarifies it's the size *without* gzip. It's 6.47kb with gzip.
