### ISSUE TITLE
Why does function returned from getEventHandler prevent from propagating event?

### ISSUE THREAD

**Issue by CoderK** [Lucifier129/react-lite#27]
I have a question about react-lite's event system. Why does function returned from getEventHandler prevent from propagating native event?

```
    var getEventHandler = function getEventHandler(handleEvent) {
    	handleEvent = eventHandlerWrapper(handleEvent);
    	return function (e) {
    		e.stopPropagation(); // This makes some side effect.
    		e.nativeEvent = e;
    		return handleEvent.call(this, e);
    	};
    };
```

I had attached native click event listener on document.body, but because of it, my event listener was never called. React doesn't do like that.

**Comment by fritx** [comment]
Related? https://github.com/Lucifier129/react-lite/issues/25

**Comment by CoderK** [comment]
Thanks, I could understand why.
It's for reducing cost of code, but It makes some side effects in one instances. ㅠ-ㅠ.

**Comment by Lucifier129** [comment]
I will consider it, and try to make them coincident in next version of react-lite

**Comment by Lucifier129** [comment]
Hi all, react-lite v0.0.19 update the event-system from dom level0 to delegation, see it at: https://github.com/Lucifier129/react-lite/blob/master/src/event-system.js

@fritx  I think binding event inside a event listener now will be called like regular react.

**Comment by fritx** [comment]
nice

**Comment by CoderK** [comment]
that sounds good!
