### ISSUE TITLE
SVG elements not showing

### ISSUE THREAD

**Issue by cezary** [Lucifier129/react-lite#29]
When using react-icons, it appears svg elements lose attribute styles. This is is a screenshot in a working dev environment
![screen shot 2016-02-07 at 4 13 25 pm](https://cloud.githubusercontent.com/assets/370808/12876351/e503c8ca-cdb5-11e5-95bf-3d81111a0601.png)

and a screenshot of a production build using react-lite where the svg does not show
![screen shot 2016-02-07 at 4 13 27 pm](https://cloud.githubusercontent.com/assets/370808/12876355/f63f75d0-cdb5-11e5-8f09-13a52532e9ee.png)

One thing I noticed is the attributes lose their camel case in the dom. I tested a production build using react and svg elements display normally. Any help to get svgs showing would be appreciated!

**Comment by albertogasparin** [comment]
+1, SVG also breaks when using d3.js

**Comment by Lucifier129** [comment]
Thanks for feedback, will try to resolve it as soon as possible: -)

**Comment by Lucifier129** [comment]
Hi guys, react-lite now support showing svg element, see demos at [REAMME](https://github.com/Lucifier129/react-lite#what-can-react-lite-do):-)

**Comment by mindreframer** [comment]
@Lucifier129 wow! That looks really awesome! This was my major blocker to use react-lite, now this seems to be a real alternative for production! Thx a lot!

**Comment by cezary** [comment]
SVGs are working now, thanks @Lucifier129! :+1:
