### ISSUE TITLE
能大概解释下生命周期如何实现的么XD

### ISSUE THREAD

**Issue by zzz6519003** [Lucifier129/react-lite#3]
:beer:

**Comment by Lucifier129** [comment]
看看 component.js 的源码，参考 react 源码里的注释描述：
https://github.com/facebook/react/blob/35962a00084382b49d1f9e3bd36612925f360e5b/src/renderers/shared/reconciler/ReactCompositeComponent.js#L50

**Comment by zzz6519003** [comment]
感觉你的实现方法似乎更简洁XD

**Comment by Lucifier129** [comment]
因为没有用 transaction ，直接明码编排触发时机。
