### ISSUE TITLE
How does react-lite compare to preact?

### ISSUE THREAD

**Issue by andyhu** [Lucifier129/react-lite#30]
https://github.com/developit/preact

**Comment by Lucifier129** [comment]
Good question!!

Both preact and react-lite are try to reduce the script size of react.

react-lite is all-in-one project intend to be a drop-in replacement for react,  no need to change any code.

preact spilt to several project and you must compose them by yourself, and now only support a few feature of React.

In this case, preact seem like react-lite-lite.
