### ISSUE TITLE
stopPropagation and event delegation

### ISSUE THREAD

**Issue by niklasbuschmann** [Lucifier129/react-lite#31]
```javascript
const Example = props =>
  <div onClick={event => console.log('outer')}>
    <span onClick={event => {event.stopPropagation(); console.log('inner');}} />
  </div>;
```
This logs first `inner` and then `outer`, same result with `event.stopImmediatePropagation()`.

I assume this is because of the event delegation, as there is only on event handler at `document` per app and event, so the native `stopImmediatePropagation` won't work, because there are no other event listeners to cancel.

How can I prevent events from propagating with react-lite?

**Comment by Lucifier129** [comment]
Thank you for feedback.

Please upgrade react-lite to v0.0.24, now it will work as expected.

**Comment by niklasbuschmann** [comment]
Thank you for the fast support, I can now replace React entirely with React-lite, this project is awesome.
