### ISSUE TITLE
Having issues in IE9/10

### ISSUE THREAD

**Issue by bjarneo** [Lucifier129/react-lite#33]
The error is:
Unable to set property 'parentContext' of undefined or null.

Which breaks the execution.

I'm not entirely sure what's causing this, but I changed my code from createClass to extend component, removed mixin and created a higher-order component instead.

https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750

**Comment by Lucifier129** [comment]
I guess babel broke them, see related infomation at  https://phabricator.babeljs.io/T3041

**Comment by bjarneo** [comment]
That might be it. But then it should be broken in react also?

**Comment by Lucifier129** [comment]
react work well with ES2015 classes, even in IE9/10. They call super constructor and add static property/method manualy.

**Comment by bjarneo** [comment]
Ah, just read the whole thread you refered to. Think I'll fix it. Thanks for your feedback.
