### ISSUE TITLE
missing removeEventListener 

### ISSUE THREAD

**Issue by himalayafan** [Lucifier129/react-lite#37]
I noticed that you are missing an important feature - to remove events from the DOM.A listener should be cleaned up when you destroy a node, and also on the nodes children.

You find it in React if you look at the *EventListener* object..

```
remove: function () {
          target.removeEventListener(eventType, callback, false);
        }
```

**Comment by Lucifier129** [comment]
When the node was destroyed, its events can'nt be GC?

**Comment by himalayafan** [comment]
... and avoid memory leaks that can occour. And also in a few rare cases the node will still be in the DOM. You only cut off the link to it - reference. And the listener will / can stil be active.

**Comment by Lucifier129** [comment]
OK, I got it.

**Comment by Lucifier129** [comment]
react-lite v0.15.0 had fixed it
