### ISSUE TITLE
why not use React v.15 ref system?

### ISSUE THREAD

**Issue by himalayafan** [Lucifier129/react-lite#38]
I notice you are using the old React v.0.13 for ref. Plans to update to support React v. 15?

**Comment by Lucifier129** [comment]
It's already support React v15.0-rc.1,

The comment at https://github.com/Lucifier129/react-lite/blob/master/src/virtual-dom.js#L399 means support the style of React v0.13, it does not mean use the old way for ref.

**Comment by Lucifier129** [comment]
Yeah, react-lite will remove getDOMNode soon.

**Comment by Lucifier129** [comment]
I change my decision, just keep the old api to support more feature.
