### ISSUE TITLE
lot of bugs

### ISSUE THREAD

**Issue by himalayafan** [Lucifier129/react-lite#39]
It seems that whatever I try to do with your code, I ran into errors, bugs or strange behaviour. 
Obviously this code is at a very early stage and not ready for production.

- TypeError: Failed to execute 'replaceChild' on 'Node': parameter 2 is not of type 'Node'.
- TypeError: Cannot read property 'childNodes' of null
- TypeError: Cannot read property 'tagName' of null

This is just a few errors I get all the time. And this is related till how you are dealing with the children, the fact you are not removing any children etc.

In your velem and the destroy function. Seems sometimes it can't find the children it should unmount. Sometimes 1 or more of the children are undefined or null.

And a lot more.

I suggest try to copy some of the stuff from Virtual DOM as I have seen you tried in the beginning, but changed from that path. They are also following React and doesnt have this errors.

React-lite is a good attempt, but not ready yet. For now I got enough because of this and performance so I move away to better solutions.

Maybe one day in the future I will check back on this repo

**Comment by himalayafan** [comment]
I was playing around a little more, so I have to add this:

- TypeError: parentElement.appendChild is not a function
- Uncaught TypeError: Cannot read property 'replace' of undefined

**Comment by himalayafan** [comment]
TypeError: Cannot read property 'tagName' of null

**Comment by Lucifier129** [comment]
Can you add some simple demos here?

**Comment by himalayafan** [comment]
I will soon.

I got some good news for you. I talked to a friend of mine. He is an expert on this and are willing to help you out. A lot of work to do he told me, but I saw his new mount code.
If you want his help, is there a place you can chat with him?

**Comment by Lucifier129** [comment]
That's great, We can talk about react-lite at https://gitter.im/Lucifier129/react-lite

**Comment by himalayafan** [comment]
I will notify him. He is occupied just now finishing a demo code, but will be there shortly.

**Comment by himalayafan** [comment]
@Lucifier129 He contacted you, but you wasn't there.

**Comment by Lucifier129** [comment]
sorry about that, I am talking with him now.

**Comment by himalayafan** [comment]
@Lucifier129 I understand that you two want to do different things.

Anyway. DId you notice what he just pushed - simple mount method? It does everything and seem to solve some of the issues I found in react lite.  

It also have an option for diffing children very smart.

**Comment by Lucifier129** [comment]
I star his project, will focus his work : )

**Comment by himalayafan** [comment]
@Lucifier129 He told me now that he wrote to you on chat, and he also solved several issues you faced with react lite. Is there anything there you can use for react lite?

**Comment by Lucifier129** [comment]
I got it.

Since that is not about the subject of this issue, let's focus the bugs you said.

Can you add some demos to show the problems?

**Comment by himalayafan** [comment]
Hi. Most of this seems to be fixed in dev branch. However. Sometimes when I update from a element node, to a text node. I get this warnings, or I get undefined instead of the node get removed.
If I then again try to re-patch the node that should have been removed, but have undefined as text, I get this errors.

So most of this errors are related to various combos I did when I do update.

**Comment by Lucifier129** [comment]
close this issue and could reopen if new error appears with a simple demo to show what happen
