### ISSUE TITLE
npm install 遇到问题，sh: node-waf: command not found

### ISSUE THREAD

**Issue by tlightsky** [Lucifier129/react-lite#4]
npm install 遇到点问题
```
 
> zlib@1.0.5 preinstall /Users/xxx/Documents/source/js/react-lite/node_modules/zlib
> node-waf clean || true; node-waf configure build

sh: node-waf: command not found
sh: node-waf: command not found
 
```

node version : ```v0.12.0```

**Comment by tlightsky** [comment]
似乎是[zlib引起的](http://stackoverflow.com/questions/24830995/npm-install-node-waf-not-found-what-to-do)

**Comment by Lucifier129** [comment]
good for you

**Comment by Aweary** [comment]
@Lucifier129 I get this error as well when trying to run `npm install`. The `zlib` package is way out of date and not maintained, it shouldn't be a dev dependency.
