### ISSUE TITLE
sort and reorder children like React 0.14 / 15

### ISSUE THREAD

**Issue by himalayafan** [Lucifier129/react-lite#41]
I noticed that many important features for dealing with children is not adopted into React lite. E.g. **insertAt()**, a function React uses for children. 

Plan to implement it?

React now also uses optimizations for Edge, when they deal with children. Added in React 15. This is not included either.

And you are not removing text nodes on diff. If nodeA have text and nodeB doesn't. nodeB will get undefined as text. In react this node are removed and reordered.

So any plans for a proper children diff algorithm ?

**Comment by Lucifier129** [comment]
working on it.

**Comment by himalayafan** [comment]
I noticed your latest changes, and was running the vdom bench. Seems like you dropped from 280 000 down till 220 000.  So a little improvement.

But still one of the slowest libraries out there. How is your plan further to get it down to 50 000 ?

**Comment by Lucifier129** [comment]
add reorder feature to react-lite at version 0.15.1.
