### ISSUE TITLE
remove use of innerHTML repalce with createElement? React 15

### ISSUE THREAD

**Issue by himalayafan** [Lucifier129/react-lite#42]
React 15 removed use of innerHTML and now uses createElement. See latest release notes.

You are still using innerHTML - wich is slow - a lot. 

Are you going to fix this?

**Comment by Lucifier129** [comment]
React-lite always use createElement, never use innerHTML to create real dom, but use to clear current childNodes of container dom.

**Comment by Lucifier129** [comment]
The first, you are wrong about the way react-lite handle vdom to react-dom

The second, you should show me the perf-test to prove what you said, and had better fork react-lite and pull request to me.

Talk is cheap!

**Comment by himalayafan** [comment]
https://jsperf.com/innerhtml-vs-removechild/394

**Comment by Lucifier129** [comment]
That is good, hope next time you open issue will show the evidences directly ; )

Will resolve it soon.

**Comment by himalayafan** [comment]
And next time I hope authors of repos I visit at least have basic knowledge about things

**Comment by Lucifier129** [comment]
Come on, if `innerHTML` vs `removeChild` is basic knowledge everyone knows, and why someboy create https://jsperf.com/innerhtml-vs-removechild/394 ?

Additionally, use innerHTML to clear container is not commonly usedery in react-lite, The improve of changing innerHTML to removeChild is very limited .

This issue  even not worth mentioning.
