### ISSUE TITLE
component data on DOM node slows down

### ISSUE THREAD

**Issue by himalayafan** [Lucifier129/react-lite#43]
Hi. I notice you are storing id and relevant component data on the DOM node itself. Any reason for this? It's a major slow down. Better is to create a virtual instance and transfer the instance on update.
Comparing to React, that is how they do it, plus they use the *owner* that you are missing.

**Comment by Lucifier129** [comment]
You don't know react, and also react-lite, both of them store data at real-dom.

**Comment by jonyy123** [comment]
I think I have more knowledge then you. In the first place I wouldnt developed a library like you have, full of bad things. And you have no reasont o say I don't react. On What reason you say that?
Easy to search React source code, and see things for myself. A lot of things in your code that break with React.

**Comment by Lucifier129** [comment]
@jonyy123 I had show you the reason above about why I said you don't know react.
