### ISSUE TITLE
Failing reordering

### ISSUE THREAD

**Issue by himalayafan** [Lucifier129/react-lite#44]
Comparing react-lite to React, I can't see any use of *keys* when I did a quick search through your source code. React uses keys to sort and re-order keyed-nodes.
I notice however that you have a silly implementation of something that suppose to be reordering, but far far from what React has and use.

If this is a small "copy" of React, why not follow what React does and implement a correct reordering?

**Comment by Lucifier129** [comment]
just keep your eyes clear, then you would see: https://github.com/Lucifier129/react-lite/blob/master/src/virtual-dom.js#L137-L187
