### ISSUE TITLE
children reconciliation

### ISSUE THREAD

**Issue by himalayafan** [Lucifier129/react-lite#45]
I can't see that you have any children reconciliation as drafted out in this specs:

https://facebook.github.io/react/docs/reconciliation.html

Any plans to implement this? It should be basic if this was a React copy.

**Comment by jonyy123** [comment]
Close this? Very important for people who use your libs. You are not even near what React have implemented. And the benchmarks - vdom - shows that your lib is very very very slow.

And you can't insert elements from first row, it will always be set in the end of parent element. 

This is far from what React does!

**Comment by Lucifier129** [comment]
benchmarks of react-lite looks well, and react use inserBefore too, just ok.
