### ISSUE TITLE
deprecated features

### ISSUE THREAD

**Issue by himalayafan** [Lucifier129/react-lite#46]
React have either deprecated or removed a lot of fetures in the upcomming React 15, that you still are using in your code. Plans to remove them?

**Comment by Lucifier129** [comment]
No, thease feature did not break the code, react-lite keep them for widely supporting.

**Comment by jonyy123** [comment]
Most of people know you are a deprecated feature, but I was more thinking of React. You seems to want to break with React . Maybe change name?

**Comment by Lucifier129** [comment]
react-lite works well with react code, it dose not break when keep some useful api.

**Comment by fightingcat** [comment]
@ghost then go and play with react, why are you still here?
