### ISSUE TITLE
DOM nodes don't have focus

### ISSUE THREAD

**Issue by himalayafan** [Lucifier129/react-lite#47]
React have a feture to keep track on DOM nodes, and keep them in focus during update. You don't have this.

*document.activeElement;*

Any plans to copy React on this one?

**Comment by Lucifier129** [comment]
NO

**Comment by jonyy123** [comment]
So you will get a lot of complains here. This is a major  feature that all libs have.
So if this is lacking, I would suggest everyone to stay away from this garbage lib anyway.

**Comment by fightingcat** [comment]
Can't stand such a garbage like you before read your suggestion! I've noticed these disscussion you started before, the author have showed patience and will embrace any positive contributions. Why do you just want to ruin something? RUIN YOURSELF!

**Comment by Dafrok** [comment]
```
ghost.dislike(reactLite).then(() => {
  if (keepAwayFromHere(ghost)) {
    all.welcome(ghost)
  } else {
   ghost.pullRequest(pr).then(() => {
    isFine(pr) ? (merge(pr), all.welcome(ghost)) : close(pr)
   ghost.issue(content).then(() => {
    isGarbage(content) ? (all.dislike(ghost), garbages.push(ghost), ruin(ghost)) : all.welcome(ghost)
  })
  }
})
```

**Comment by Lucifier129** [comment]
@Dafrok Excellent code!!
