### ISSUE TITLE
Boolean false props not handled the same as React

### ISSUE THREAD

**Issue by rgrwkmn** [Lucifier129/react-lite#48]
Using react-bootstrap, attributes are being added to the rendered components that are not present with React. For example, here is the rendered result of a react-bootstrap Button with default props:

```html
<a bsstyle="default" bsclass="btn" active="false" block="false" disabled="false" navitem="false" navdropdown="false" href="/accounts/users/add" class="btn btn-default" role="button">Add New User</a>
```

All the `false` attributes actually shouldn't be there.

**Comment by Lucifier129** [comment]
react-lite simply setAttribute if !(propName in elem) return true
https://github.com/Lucifier129/react-lite#react-lite-vs-react

**Comment by Lucifier129** [comment]
I think react-lite v0.15.6 made consistent with regular react about handling props.
