### ISSUE TITLE
Question: why would I be fired for using React.__SECRET_DOM_DO_NOT_USE_OR_YOU_WILL_BE_FIRED?

### ISSUE THREAD

**Issue by capaj** [Lucifier129/react-lite#5]
https://github.com/Lucifier129/react-lite/blob/master/dist/react-lite.common.js#L1395

**Comment by Lucifier129** [comment]
haha, this is ReactDOM, copy from react source code, see this link
https://github.com/facebook/react/blob/master/src/React.js#L67

**Comment by capaj** [comment]
Lol.

**Comment by webveloper** [comment]
While I appreciate the humor, I see two reasons to consider changing this:

First, it's inefficient.  It's a very long variable name that isn't replaced during minification, so it's technically wasting bandwidth.  Not much, of course, but when else in programming would you intentionally do something less efficient for no apparent gain?  `__SECRET_DOM` would be 72.7% smaller.  If there really is a problem with developers using it, `__SECRET_DOM_DO_NOT_USE` would be 47.7% smaller.  Even at a small scale, I couldn't pass up that kind of savings.

Second, if someone considering employment with a company views that company's source, sees that variable name, and thinks it's something the company added themselves... maybe not so great.

**Comment by desarrollador-lata13** [comment]
Hi, I am new in this app.

**Comment by alexander-grube** [comment]
lol
