### ISSUE TITLE
React.__spread support

### ISSUE THREAD

**Issue by VinSpee** [Lucifier129/react-lite#51]
Hi!

I'm using react-lite along side of [react-typeahead](https://github.com/fmoo/react-typeahead/blob/321db82b62d8d3a1e6c14ce6d26cf6d1e0cbb556/dist/react-typeahead.js#L806).

It digs into `React.__spread`, which is just an Object.assign polyfill. Is it possible / valuable enough to add that method to react-lite?

https://github.com/facebook/react/blob/6a8ebfc41842fb200c87a919478dcd3aa95be0d7/src/isomorphic/React.js#L70

**Comment by Lucifier129** [comment]
JSX spread just works well when use webpack, it seems like browserify do somethings differently in it.

Can you switch to webpack?

Or build your own react-lite like below:

```javascript
// react-lite-with-spreed-hook.js
var React = require('react-lite')
var assign = require('object.assign')
module.exports = assign({
  __spread: assign
}, React)
```

Then use alias `react-lite-with-spreed-hook` for `react/react-dom`.

**Comment by VinSpee** [comment]
I am actually using require.js (w/o JSX) (soon will be migrating to webpack, but not an option quite yet). I will try shimming as you suggested, thanks!

It may be a good idea to mention that react-lite only works with a JSX toolchain?

**Comment by Lucifier129** [comment]
That will be good, I add the notice at https://github.com/Lucifier129/react-lite#react-lite-vs-react

**Comment by VinSpee** [comment]
awesome, thanks!
