### ISSUE TITLE
avoid script|head|link tag in client side

### ISSUE THREAD

**Issue by firephoenix7921** [Lucifier129/react-lite#55]
why use react-lite, avoid script|head|link tag in client side.  Dose it cause performance problems ?

**Comment by Lucifier129** [comment]
When use server side rendering, browser will load script/link sources, if react-lite render script/link, they will be loaded twice.

**Comment by firephoenix7921** [comment]
when react-lite render script/link, what does react-lite do specifically？  js will execute again?

**Comment by firephoenix7921** [comment]
react-lite渲染script/link标签的时候具体做了什么呢？

**Comment by Lucifier129** [comment]
我的意思是，服务端渲染时 html 字符串里已经有 script\link 的请求了，浏览器端再 document.createElement + appendChild 相同的 script\link ，浏览器会再请求一遍。

这不是 react-lite 做了特别的事情，而是 react 做了特别的事情，继承了服务端渲染的 dom 结构，不会重新创建 dom。而 react-lite 没有这部分内容，是重新替换整个 dom 树。
