### ISSUE TITLE
Event System event.persist()

### ISSUE THREAD

**Issue by sthzg** [Lucifier129/react-lite#58]
I just tried building a browser bundle with react-lite and immediately got a bundle 100k smaller than before 🎉 .

One thing that breaks is code that invokes `event.persist()` (see https://facebook.github.io/react/docs/events.html#event-pooling): `Uncaught TypeError: e.persist is not a function`.

Is this expected and if yes, should it be added to "versus"-section in the README?

**Comment by Lucifier129** [comment]
I just set `event.persist`as no-op function to avoid throwing error, because `event` object in react-lite is always persistent.

And note the different in the README.

**Comment by sthzg** [comment]
@Lucifier129 that is great news, thank you! I will try it with the new release as soon as possible.
