### ISSUE TITLE
browser compatibility compared to standard react?

### ISSUE THREAD

**Issue by pkieltyka** [Lucifier129/react-lite#6]
amazing work btw!

**Comment by Lucifier129** [comment]
react-lite can support IE8+ even without es5-shim/es5-sham.

**Comment by mindreframer** [comment]
can be closed, info is in the readme: https://github.com/Lucifier129/react-lite/pull/21

**Comment by andyhu** [comment]
IE8+ or IE9+?

**Comment by Lucifier129** [comment]
@andyhu Did you read this [doc](https://github.com/xcatliu/react-ie8#cn-make-your-react-app-work-in-ie8)?
