### ISSUE TITLE
How to enable production mode?

### ISSUE THREAD

**Issue by PierBover** [Lucifier129/react-lite#67]
Does `react-lite` have a dev and production mode like React?

With Webpack I use this:

```
new webpack.DefinePlugin({
  "process.env": { 
     NODE_ENV: JSON.stringify("production") 
   }
})
```

Does this also work with `react-lite`?

**Comment by Lucifier129** [comment]
It can work, but does not optmize anything. 

`react-lite` have no production mode, it writes for runing in production.

**Comment by PierBover** [comment]
Awesome, thanks for the clarification.
