### ISSUE TITLE
Use with react-worker-dom ?

### ISSUE THREAD

**Issue by azizzaeny** [Lucifier129/react-lite#71]
instead using react.render can we use ReactDOM default renderer... for initial render instead use it inside react tree.. or use it as aliases ? 
eg:  eact-worker-dom and use react lite to work too...

``` es6
import React from 'react';
import reactDOM from 'react-worker-dom'; // Instead of using react-dom
reactDOM.render(new Worker('worker.js'), document.getElementById('container'));
```

many clojurescript React wrapper also use ReactDOM..

**Comment by Lucifier129** [comment]
I think `react-lite` can't work with `react-worker-dom`.

**Comment by azizzaeny** [comment]
Ok... would it have some issue... if i just use react-dom from react to render react-lite...?
react-dom only contain with : 
```js
(function(React) {
  return React.__SECRET_DOM_DO_NOT_USE_OR_YOU_WILL_BE_FIRED;
});
```
React API support React.render only until 0.14.. can we make best practices for others to use react-dom ... instead aliases,  React 0.15 above will show deprecated warning...

because its consisten..., preserving others API such as clojurescript Reagent OM...

till now i still doesn't know why react separating two global js like that... 
but people follow it, and it become future culture... and accepted

**Comment by Lucifier129** [comment]
Once `react-lite` can use `react-dom` directly without `alias` by [React.__SECRET_DOM_DO_NOT_USE_OR_YOU_WILL_BE_FIRED](https://github.com/Lucifier129/react-lite/blob/master/src/index.js#L25), but `react-dom` changed its `npm package`, it would [require](https://github.com/facebook/react/blob/master/packages/react-dom/index.js) `react/lib/ReactDOM`.

**Comment by azizzaeny** [comment]
i think i can make it... using cdn version: 
```js 
(function(f) {
  // CommonJS
  if (typeof exports === "object" && typeof module !== "undefined") {
    module.exports = f(require('react'));

  // RequireJS
  } else if (typeof define === "function" && define.amd) {
    define(['react'], f);

  // <script>
  } else {
    var g;
    if (typeof window !== "undefined") {
      g = window;
    } else if (typeof global !== "undefined") {
      g = global;
    } else if (typeof self !== "undefined") {
      g = self;
    } else {
      // works providing we're not in "use strict";
      // needed for Java 8 Nashorn
      // see https://github.com/facebook/react/issues/3037
      g = this;
    }
    g.ReactDOM = f(g.React);
  }

})(function(React) {
  return React.__SECRET_DOM_DO_NOT_USE_OR_YOU_WILL_BE_FIRED;
});
```
use aliases can also work with clojurescript:
```js
; before rendering
(set! js/ReactDOM js/React)
```

Overall thanks....., 
I just figure how to implement virtual-dom rendering and patching in web-worker... 
then i came across your react-lite because its small size really fit in web-worker to bundle... 

Unfortunetly to make it work... we need some heavy work to implement separation context between main thread and worker thread.... because worker env doesnt allow us to write DOM...

check this out 
- [feather-app](https://github.com/HenrikJoreteg/feather-app)... 
- [presentation](https://glebbahmutov.com/blog//buzzjs/)

**Comment by Lucifier129** [comment]
They look interesting~
