### ISSUE TITLE
react-tap-event-plugin with react-lite

### ISSUE THREAD

**Issue by k0r8i** [Lucifier129/react-lite#72]
Hi there!
Any chance to get react-tap-event-plugin work with react-lite?
It apparently depends on:
- EventPluginHub
- EventConstants
- EventPluginUtils
- EventPropagators
- SyntheticUIEvent
- ViewportMetrics
Webpack with alias set to react-lite will therefore fail since react-lite does not contain any of the above mentioned.

Hints more than appreciated!

Cheers
Korbi

**Comment by Lucifier129** [comment]
I am very sorry to say that react-lite can't support `react-tap-event-plugin`, I use `fastclick` to resolve the same problem.
