### ISSUE TITLE
Compatibility with react-widgets

### ISSUE THREAD

**Issue by saxicek** [Lucifier129/react-lite#76]
Currently react-widgets fail with react-lite, because react-widgets uses following invariant:
https://github.com/jquense/uncontrollable/blob/master/src/createUncontrollable.js#L25 which requires `component.prototype.isReactComponent` on the component (https://github.com/jquense/uncontrollable/blob/master/src/utils.js#L100).

Is it possible to add this attribute?

**Comment by Lucifier129** [comment]
It's ok, and done with this [commit](https://github.com/Lucifier129/react-lite/commit/054ba2916d673517d8e5b7f1817b3c32e8e09850), please try to use the lastest version(0.15.23) of react-lite and feedback if something wrong.

**Comment by saxicek** [comment]
The issue is resolved, thank you!
