### ISSUE TITLE
not work with react-boilerplate?

### ISSUE THREAD

**Issue by mydearxym** [Lucifier129/react-lite#77]
amazing work !

i use react-lite with [react-boilerplate](https://github.com/mxstbr/react-boilerplate) , it did shrink the build size, but got this error in brower (regular react works fine): 

![image](https://cloud.githubusercontent.com/assets/6184465/19467553/57af5618-9544-11e6-830f-836040b30eed.png)

[webpack config](https://github.com/mydearxym/coder_club_frontend/blob/react-lite/internals/webpack/webpack.base.babel.js#L89-L92)

### Reproduce:
check out [a demo for this issue](https://github.com/mydearxym/coder_club_frontend/tree/react-lite) if you have time,  then `npm install && npm run build && cd ./build`

**Comment by Lucifier129** [comment]
I will check it as soon;-)

**Comment by Lucifier129** [comment]
[This line cause the problem](https://github.com/mydearxym/coder_club_frontend/blob/react-lite/package.json#L89), remove it and re-build, `react-boilerplate ` works well in my machine.

`react-lite` can't work with `transform-react-inline-elements`, you will get a bundle include both `react` and `react-lite`.

**Comment by mydearxym** [comment]
it worked! thanks for point out that .

according to [transform-react-inline-elements doc](https://babeljs.io/docs/plugins/transform-react-inline-elements/), this plugin : 

> Replaces the React.createElement function with a more optimized one for production...


it's  this `more optimized one for production` matters ?

**Comment by Lucifier129** [comment]
I do'nt think it matters, but you can switch `react/react-lite` to see the different and feel free to make you own choice.

**Comment by mydearxym** [comment]
thanks @Lucifier129  

and i suggest add this babel limitation to readme or doc

**Comment by Lucifier129** [comment]
Yeah, I done it yesterday. Click [here](yesterday) and see the last one.

**Comment by mydearxym** [comment]
cool 👍
