### ISSUE TITLE
Document where this repo diverges from regular ReactJS

### ISSUE THREAD

**Issue by davezuko** [Lucifier129/react-lite#8]
Hey, great project!

I'm just about to start reading through the source to figure out exactly what the tradeoffs are (beyond losing out on server-side rendering). This definitely looks like it  could be a sane alternative to the core library, especially for smaller projects, but it would be nice to know up front just what the differences are so people don't run into a wall down the road.

That is unless the only difference is the loss of `renderToString`/`renderToStaticMarkup`, which I find doubtful, but it'd be nice to know for sure straight from the documentation.

Thanks!

**Comment by Lucifier129** [comment]
Good suggestion. 

I have added `react-lite vs react` part in README

https://github.com/Lucifier129/react-lite#react-lite-vs-react

**Comment by davezuko** [comment]
:+1: thank you very much!
