### ISSUE TITLE
missed ReactInputSelection

### ISSUE THREAD

**Issue by alexeybondarenko** [Lucifier129/react-lite#81]
ReactInputSelection is used inside input mask packages, such as react-maskedinput.

Can u add it?

**Comment by Lucifier129** [comment]
Sorry. `react-lite` can not support `react-maskedinput`, because it access `[regular-react's internal module](https://github.com/insin/react-maskedinput/blob/master/src/index.js#L2)`

`react-lite` can supoort the core public api of react and keep the scripts size smaller.

**Comment by alexeybondarenko** [comment]
Thank you for an answer. I think I will try to fix masked-input for my project.
