### ISSUE TITLE
References in stateless components don't work (but do in full react)

### ISSUE THREAD

**Issue by sceutre** [Lucifier129/react-lite#84]
I encountered this when trying to use drop down menus from http://blueprintjs.com.  Here is a small example:

```
class Wrapper extends React.Component {
   render() {
       return <div><Stateless /></div>;
  }
}

function setRef(c) {
   console.log("ref from a stateless component", c);
}

const Stateless = (props) => <div ref={setRef}>Hello, world</div>;
```

When rendered, the console log displays in full react but not react-lite.

Looking at the code, I can fix it by doing the following, but I'm not sure if this is the best solution or has any other impacts:
1. Remove the velem.refs check in initVelem
2. in attachRef and detachRef move the refs check to the bottom of the method (eg just before they are used).

**Comment by Lucifier129** [comment]
Thx feedback, I think you are totally right.

 And fixed it at this [commit](https://github.com/Lucifier129/react-lite/commit/e9ff31d3301b791fea3c43fde5146dceb13dacbe), now the version 0.15.28 of `react-lite` support this pattern.

**Comment by sceutre** [comment]
Thanks!  Works for me now.
