### ISSUE TITLE
Repos for tests in your article?

### ISSUE THREAD

**Issue by trueadm** [Lucifier129/react-lite#86]
Please could you link reference repos for your test experiments for React-lite, Preact and Inferno for this article (when running them against React):

https://medium.com/@guyingjie129/why-you-shouldnt-use-preact-and-inferno-to-replace-react-4000ffb44572#.jvaxfr8z5

Thank you! :)

**Comment by Lucifier129** [comment]
Added it now, visit [this repos](https://github.com/Lucifier129/react-core-unit-testing);)
