### ISSUE TITLE
styled-components  error

### ISSUE THREAD

**Issue by mydearxym** [Lucifier129/react-lite#89]
there is some error when use [styled-components
](https://github.com/styled-components/styled-components)

```js
Module not found: Error: Can't resolve 'react/lib/HTMLDOMPropertyConfig' in '/Users/xieyiming/code/coder_club/front_end/node_modules/styled-components/lib/utils'
```

```js
ERROR in ./~/styled-components/lib/utils/validAttr.js
Module not found: Error: Can't resolve 'react/lib/SVGDOMPropertyConfig' in '/Users/xieyiming/code/coder_club/front_end/node_modules/styled-components/lib/utils'
```

**Comment by Lucifier129** [comment]
Thx feedback. `react-lite` can't support the internal module of `react`, so `require('react/lib/**')` will not work.

And they also not allow by `react v~15.4.0`, visit [here](https://github.com/reactjs/core-notes/blob/master/2016-10/october-13.md#releasing-1540) for more detail

**Comment by mydearxym** [comment]
update the latest version of  `styled-components` solve the issue , thanks !
