### ISSUE TITLE
react router huge apps not working

### ISSUE THREAD

**Issue by afaayerhan** [Lucifier129/react-lite#9]
the example with react router huge apps is not working when you click the link to a course http://react-lite-with-react-router.coding.io/huge-apps/course/1 http://react-lite-with-react-router.coding.io/huge-apps/

**Comment by Lucifier129** [comment]
yeah, that's a problem; but even use regular react, it could'nt work too. 

so i think this is not the problem about react-lite, probably is the huge-app example itself.
