### ISSUE TITLE
使用react-router v4的Redirect的时候，会出现页面空白的情况

### ISSUE THREAD

**Issue by KevisLuo** [Lucifier129/react-lite#91]
<Match pattern='/' exactly render={props => (
      <Redirect to={{
              pathname: '/user/login'
      }} />
)} />
从一个路由重定向到另外一个路由的时候，页面会出现空白的现象，切换为react是正常的

**Comment by Lucifier129** [comment]
Fixed in `react-lite` v0.15.30
