### ISSUE TITLE
Server side generated HTML is completely rerendered

### ISSUE THREAD

**Issue by rsadyhov** [Lucifier129/react-lite#92]
I found out that there is no benefit of server side rendering with React as React Lite completely removes main node from browser DOM and substitutes it with what is rendered on UI during first page load.

This can be seen during debug of react-lite.common.js on line #1923. Per my understanding this logic is executed all the time after page load and there is no way to omit it.

It's causing troubles for our project as we do have other mechanisms in parallel to React, which are changing the browser DOM. As result our changes our wiped out and we need to rely on React Lite lifecycle, which is causing performance degradation.

It would be great to have similar mechanism which exists in React and compares checks sums of server side generated content and content of UI side rendered virtual DOM. So if they are equal, it will just perform component mounting, but not full rerender.

**Comment by Lucifier129** [comment]
Sorry about that.

This inconsistent behaviour was mentioned README, visit [different with React](https://github.com/Lucifier129/react-lite#react-lite-vs-react)

**Comment by rsadyhov** [comment]
Thank you for the quick response!
